"""unify time attributes

Revision ID: b1421c341e3e
Revises: f93f6b186d60
Create Date: 2021-06-24 15:05:50.555341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1421c341e3e'
down_revision = 'f93f6b186d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_tokens', 'expired_in',
               existing_type=mysql.INTEGER(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_verifications', 'expired_in',
               existing_type=mysql.INTEGER(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'date_joined',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_joined',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('email_verifications', 'expired_in',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('auth_tokens', 'expired_in',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
